name: Lint, test, and scan Helm charts
on:
  pull_request:
    branches:
      - master
      - release/**
  workflow_dispatch:
jobs:
  lint-test-scan:
    uses: Cray-HPE/.github/.github/workflows/charts-lint-test-scan.yml@main
    with:
      lint-charts: ${{ github.event_name == 'pull_request' }}
      ct-config: |
        chart-dirs:
          - kubernetes
      scan-chart-snyk-args: "--severity-threshold=high --policy-path=kubernetes/.snyk"
      scan-image-snyk-args: "--severity-threshold=high"
      test-charts: false
      scan-images: false
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      artifactory-username: ${{ secrets.ARTIFACTORY_ALGOL60_READONLY_USERNAME }}
      artifactory-password: ${{ secrets.ARTIFACTORY_ALGOL60_READONLY_TOKEN }}
